require 'devextreme/rails'
require 'renderers/data_table_json_renderer'
require 'renderers/data_table_csv_renderer'
require 'renderers/data_table_xls_renderer'
require 'renderers/data_table_xml_renderer'
require 'data_table'
require 'data_table_formatters'